# Generated by Django 4.0.5 on 2022-08-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
