# Generated by Django 4.0.5 on 2022-07-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('person', models.CharField(max_length=10)),
            ],
        ),
    ]
