# Generated by Django 4.0.5 on 2022-07-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reservation_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='email',
            new_name='reg_email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='reg_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='person',
            new_name='reg_person',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='reg_phone',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='reg_time',
        ),
    ]
