# Generated by Django 4.0.5 on 2022-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_date_reservation_reg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reg_name',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
