# Generated by Django 4.0.5 on 2022-07-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
