# Generated by Django 4.0.5 on 2022-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(null=True, upload_to='menu/icons'),
        ),
    ]
